### ISSUE TITLE
Issue with repeatable components

### ISSUE THREAD

**Issue by DimDev** [colton75/strapi-plugin-ckeditor5#1]
Steps to reproduce:
1. Create the content type with repeatable component
2. Add Rich text field to the component, switch to component Advanced settings and set Minimum value to 2
3. Save and try to add the new content item of the content type we just created

Actual: CKEditor is displayed, but most buttons don't work. Arrow keys don't work, if type and select some text and click "B" to make text bold - it also doesn't work

Expected: all CKEditor functionality works for each instance on the page.

**Comment by colton75** [comment]
#https://github.com/strapi/strapi/issues/11849#issue-1074462329

**Comment by rajatdangat** [comment]
There seems to be a problem with the new strapi frontend. The styles are getting applied but they are not visible in the preview because they are getting overridden by some other styles.

**Comment by derrickmehaffy** [comment]
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by rajatdangat** [comment]
I have fixed the issue. Install the latest version and everything should work fine. Closing this issue now.
